In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [26]:
X1 = [5.935, 1.523, 2.599, 4.009, 4.687, 8.044, 2.766, 6.538, 6.451, 3.314, 3.777, 1.530, 2.768, 6.585]
X2 = [14.2, 13.1, 12.7, 15.2, 14.7, 15.6, 13.3, 17.0, 12.9, 12.2, 13.0, 13.8, 13.6, 14.9]
X3 = [2.265, 0.597, 1.237, 1.649, 2.312, 3.641, 1.244, 2.618, 3.147, 1.606, 2.119, 0.798, 1.336, 2.763]
X4 = [2.27, 0.75, 1.11, 0.81, 2.50, 4.51, 1.03, 2.39, 5.52, 2.18, 2.83, 0.84, 1.75, 1.91]
X5 = [2.91, 2.62, 1.72, 3.02, 2.22, 2.36, 1.97, 1.85, 2.01, 1.82, 1.80, 4.25, 2.64, 3.17]
data = {'X1': X1, 'X2': X2, 'X3': X3, 'X4': X4, 'X5': X5}

In [27]:
pd_data = pd.DataFrame(data)
pd_data

X1    X2     X3    X4    X5
0   5.935  14.2  2.265  2.27  2.91
1   1.523  13.1  0.597  0.75  2.62
2   2.599  12.7  1.237  1.11  1.72
3   4.009  15.2  1.649  0.81  3.02
4   4.687  14.7  2.312  2.50  2.22
5   8.044  15.6  3.641  4.51  2.36
6   2.766  13.3  1.244  1.03  1.97
7   6.538  17.0  2.618  2.39  1.85
8   6.451  12.9  3.147  5.52  2.01
9   3.314  12.2  1.606  2.18  1.82
10  3.777  13.0  2.119  2.83  1.80
11  1.530  13.8  0.798  0.84  4.25
12  2.768  13.6  1.336  1.75  2.64
13  6.585  14.9  2.763  1.91  3.17

In [28]:
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [29]:
x = StandardScaler().fit_transform(pd_data)
x = pd.DataFrame(x, columns=['X1','X2','X3','X4','X5'])
x

X1        X2        X3        X4        X5
0   0.805870  0.144964  0.362672  0.072890  0.665895
1  -1.400165 -0.713671 -1.571798 -1.051095  0.242144
2  -0.862157 -1.025902 -0.829556 -0.784888 -1.072947
3  -0.157145  0.925542 -0.351737 -1.006728  0.826629
4   0.181860  0.535253  0.417180  0.242967 -0.342341
5   1.860387  1.237773  1.958494  1.729290 -0.137771
6  -0.778655 -0.557555 -0.821437 -0.844046 -0.707644
7   1.107375  2.330581  0.772065  0.161626 -0.882990
8   1.063874 -0.869786  1.385575  2.476149 -0.649196
9  -0.504651 -1.416191 -0.401606  0.006338 -0.926826
10 -0.273147 -0.791729  0.193348  0.486990 -0.956050
11 -1.396665 -0.167267 -1.338688 -0.984544  2.623920
12 -0.777655 -0.323382 -0.714740 -0.311631  0.271368
13  1.130875  0.691369  0.940229 -0.193317  1.045811

In [44]:
pca_init = PCA(n_components=len(pd_data.columns))

In [45]:
pca_init.fit(x)

PCA(n_components=5)

In [46]:
pca_init.explained_variance_

array([3.26188806, 1.39045626, 0.61649071, 0.10273683, 0.01304352])

In [47]:
pca_init.explained_variance_ratio_

array([0.60577921, 0.25822759, 0.11449113, 0.0190797 , 0.00242237])

In [48]:
pca_init.get_covariance()

array([[ 1.07692308,  0.65713183,  1.0454051 ,  0.7969057 , -0.18519289],
       [ 0.65713183,  1.07692308,  0.53232734,  0.10273053,  0.20022984],
       [ 1.0454051 ,  0.53232734,  1.07692308,  0.91319299, -0.26832875],
       [ 0.7969057 ,  0.10273053,  0.91319299,  1.07692308, -0.38553457],
       [-0.18519289,  0.20022984, -0.26832875, -0.38553457,  1.07692308]])

In [49]:
pd_data.corr()

X1        X2        X3        X4        X5
X1  1.000000  0.610194  0.970733  0.739984 -0.171965
X2  0.610194  1.000000  0.494304  0.095393  0.185928
X3  0.970733  0.494304  1.000000  0.847965 -0.249162
X4  0.739984  0.095393  0.847965  1.000000 -0.357996
X5 -0.171965  0.185928 -0.249162 -0.357996  1.000000

In [50]:
pca_init.get_precision()

array([[ 3.12562977e+01, -2.62496699e+00, -3.42209329e+01,
         5.94819077e+00, -5.34101555e-01],
       [-2.62496699e+00,  2.80114228e+00, -8.42195787e-01,
         2.25524060e+00, -3.74687501e-01],
       [-3.42209329e+01, -8.42195787e-01,  4.61633935e+01,
        -1.33907806e+01,  9.80122224e-01],
       [ 5.94819077e+00,  2.25524060e+00, -1.33907806e+01,
         7.67161816e+00,  1.35002445e-02],
       [-5.34101555e-01, -3.74687501e-01,  9.80122224e-01,
         1.35002445e-02,  1.15543219e+00]])

In [51]:
np.sqrt(pca_init.explained_variance_)

array([1.80606978, 1.1791761 , 0.78516923, 0.32052586, 0.11420822])

In [55]:
pca_init.explained_variance_ratio_[pca_init.explained_variance_ >= 1]

array([0.60577921, 0.25822759])