In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [13]:
data = pd.read_csv('../../mvadata/favoritesujects.csv').iloc[:,1:]
data.transpose()

0    1    2    3    4    5    6    7    8    9    ...  290  291  292  \
BIO     1    4    2    2    3    1    3    4    2    2  ...    3    3    4   
GEO     1    4    1    3    1    1    3    3    1    3  ...    5    3    3   
CHEM    1    3    3    2    2    1    3    4    3    3  ...    3    1    4   
ALG     1    4    4    4    2    4    2    2    3    2  ...    3    5    3   
CALC    1    4    1    4    3    4    3    3    4    3  ...    4    5    4   
STAT    1    4    1    3    4    4    1    2    3    4  ...    2    2    4   

      293  294  295  296  297  298  299  
BIO     1    3    1    1    3    2    3  
GEO     1    3    1    1    4    2    3  
CHEM    1    3    1    1    4    2    3  
ALG     5    2    1    3    2    5    5  
CALC    3    2    1    3    4    4    5  
STAT    3    3    1    1    5    4    5  

[6 rows x 300 columns]

In [76]:
from factor_analyzer import FactorAnalyzer
fa = FactorAnalyzer(method='ml')

In [77]:
# 적합
fa.fit(data)

FactorAnalyzer(method='ml', rotation_kwargs={})

In [78]:
ev, v = fa.get_eigenvalues()

In [79]:
ev

array([2.78672826, 1.77778185, 0.63046377, 0.33664744, 0.2621086 ,
       0.20627009])

In [80]:
ev/sum(ev)

array([0.46445471, 0.29629698, 0.10507729, 0.05610791, 0.04368477,
       0.03437835])

In [81]:
fa_varimax = FactorAnalyzer(n_factors=2, rotation='varimax', method='ml')
fa_varimax.fit(data)

FactorAnalyzer(method='ml', n_factors=2, rotation='varimax', rotation_kwargs={})

In [82]:
fa_varimax.get_factor_variance()

(array([2.12440789, 1.86311993]),
 array([0.35406798, 0.31051999]),
 array([0.35406798, 0.66458797]))

In [83]:
fa_varimax.loadings_

array([[0.85456218, 0.13257078],
       [0.77932796, 0.13455083],
       [0.86460889, 0.05545418],
       [0.03133501, 0.79070486],
       [0.09671634, 0.97107824],
       [0.16998486, 0.50612123]])

In [84]:
fa.loadings_

array([[ 0.84606402,  0.05355398, -0.03750408],
       [ 0.77594153,  0.03977838,  0.00369147],
       [ 0.89982681, -0.09837621,  0.04477106],
       [ 0.01868688,  0.29976808,  0.78644161],
       [-0.07203889,  0.87086045,  0.10764171],
       [ 0.04142764,  0.57953091, -0.04761265]])

In [32]:
FactorAnalyzer(n_factors=2, rotation=None, method='principal').fit(data).loadings_

/usr/local/lib/python3.9/site-packages/sklearn/utils/extmath.py:368: FutureWarning: If 'random_state' is not supplied, the current default is to use 0 as a fixed seed. This will change to  None in version 1.2 leading to non-deterministic results that better reflect nature of the randomized_svd solver. If you want to silence this warning, set 'random_state' to an integer seed or to None explicitly depending if you want your code to be deterministic or not.
  warnings.warn(


array([[ 0.78230188, -0.4538988 ],
       [ 0.77117922, -0.41643707],
       [ 0.74777143, -0.51261891],
       [ 0.54724649,  0.70076193],
       [ 0.63507108,  0.66447311],
       [ 0.56396677,  0.45051965]])

In [61]:
fa_promax = FactorAnalyzer(n_factors=2, rotation='promax', method='ml')
fa_promax.fit(data)

FactorAnalyzer(method='ml', n_factors=2, rotation_kwargs={})

In [62]:
fa_promax.get_factor_variance()

(array([2.14826428, 1.88768463]),
 array([0.35804405, 0.31461411]),
 array([0.35804405, 0.67265815]))

In [63]:
fa_promax.loadings_

array([[ 0.85983213,  0.01728205],
       [ 0.78206276,  0.02984049],
       [ 0.88187748, -0.06365976],
       [-0.08770075,  0.81114717],
       [-0.04774378,  0.98804396],
       [ 0.09824484,  0.49824927]])