In [2]:
hald.data <- read.table('../data2020/hald.txt', header = T)

In [3]:
head(hald.data)

X1 X2 X3 X4 Y    
1  7 26  6 60  78.5
2  1 29 15 52  74.3
3 11 56  8 20 104.3
4 11 31  8 47  87.6
5  7 52  6 33  95.9
6 11 55  9 22 109.2

In [11]:
# lm = 회귀분석
hald.ls <- lm(formula = Y ~ X1 + X2 + X3 + X4, data = hald.data)

In [12]:
hald.ls


Call:
lm(formula = Y ~ X1 + X2 + X3 + X4, data = hald.data)

Coefficients:
(Intercept)           X1           X2           X3           X4  
    62.4054       1.5511       0.5102       0.1019      -0.1441  


In [13]:
summary(hald.ls)


Call:
lm(formula = Y ~ X1 + X2 + X3 + X4, data = hald.data)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.1750 -1.6709  0.2508  1.3783  3.9254 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept)  62.4054    70.0710   0.891   0.3991  
X1            1.5511     0.7448   2.083   0.0708 .
X2            0.5102     0.7238   0.705   0.5009  
X3            0.1019     0.7547   0.135   0.8959  
X4           -0.1441     0.7091  -0.203   0.8441  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 2.446 on 8 degrees of freedom
Multiple R-squared:  0.9824,	Adjusted R-squared:  0.9736 
F-statistic: 111.5 on 4 and 8 DF,  p-value: 4.756e-07


In [14]:
# anova = 분산분석
anova(hald.ls)

Df Sum Sq       Mean Sq      F value      Pr(>F)      
X1        1  1450.0763281 1450.0763281 242.36791816 2.887559e-07
X2        1  1207.7822656 1207.7822656 201.87052753 5.863323e-07
X3        1     9.7938691    9.7938691   1.63696188 2.366003e-01
X4        1     0.2469747    0.2469747   0.04127972 8.440715e-01
Residuals 8    47.8636394    5.9829549           NA           NA

In [16]:
a <- 1:10
a

[1]  1  2  3  4  5  6  7  8  9 10

In [18]:
a <- 20:10
a

[1] 20 19 18 17 16 15 14 13 12 11 10

In [19]:
a %/% 3

[1] 6 6 6 5 5 5 4 4 4 3 3

In [20]:
a %% 3

[1] 2 1 0 2 1 0 2 1 0 2 1

In [22]:
a <- 1:3 == 3:1
a

[1] FALSE  TRUE FALSE

In [23]:
x <- -5:5
x
mean(x)

[1] -5 -4 -3 -2 -1  0  1  2  3  4  5

[1] 0

In [24]:
x[x<0]

[1] -5 -4 -3 -2 -1

In [26]:
x[x<0] <- 0
x

[1] 0 0 0 0 0 0 1 2 3 4 5

In [28]:
consec <- 1:10 * 10
consec

[1]  10  20  30  40  50  60  70  80  90 100

In [29]:
consec[2]

[1] 20

In [30]:
consec[c(3,6,8,10)]

[1]  30  60  80 100

In [31]:
consec[c(-2,-4)]

[1]  10  30  50  60  70  80  90 100

In [33]:
x <- 10:1
x

[1] 10  9  8  7  6  5  4  3  2  1

In [34]:
x[consec<60]

[1] 10  9  8  7  6

In [35]:
# seq
seq(-pi,pi,1)
# seq(-pi,pi)와 같다

[1] -3.1415927 -2.1415927 -1.1415927 -0.1415927  0.8584073  1.8584073  2.8584073

In [37]:
seq(-pi,pi,length=10)

[1] -3.1415927 -2.4434610 -1.7453293 -1.0471976 -0.3490659  0.3490659
 [7]  1.0471976  1.7453293  2.4434610  3.1415927

In [38]:
rnorm(10,-5,2.5)

[1] -6.666000 -2.270857 -5.912502 -5.540191 -2.596391 -3.957723 -2.858270
 [8] -6.374454 -1.134757 -6.393748

In [39]:
x <- 1:12
x <- matrix(x, ncol=4, byrow=T)
x

[,1] [,2] [,3] [,4]
[1,] 1     2    3    4  
[2,] 5     6    7    8  
[3,] 9    10   11   12

In [40]:
x <- matrix(1, nrow=4, ncol=3)
x

[,1] [,2] [,3]
[1,] 1    1    1   
[2,] 1    1    1   
[3,] 1    1    1   
[4,] 1    1    1

In [41]:
x <-1:12
x <- matrix(x, nco=4, byrow=T)
x[,1:3]

[,1] [,2] [,3]
[1,] 1     2    3  
[2,] 5     6    7  
[3,] 9    10   11

In [42]:
x[1:3,-2]

[,1] [,2] [,3]
[1,] 1     3    4  
[2,] 5     7    8  
[3,] 9    11   12

In [46]:
x <- matrix(c(1:3,5:7),ncol=3,byrow=T)
x

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 5    6    7

In [48]:
y <- matrix(1:4,ncol=2)
y

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [49]:
t(x)

[,1] [,2]
[1,] 1    5   
[2,] 2    6   
[3,] 3    7

In [50]:
t(x) %*% y

[,1] [,2]
[1,] 11   23  
[2,] 14   30  
[3,] 17   37

In [51]:
apply(x, 1, mean)

[1] 2 6

In [53]:
apply(x, 2, mean)

[1] 3 4 5

In [54]:
squareF <- function(x){
    x*x
}

In [55]:
squareF(4)

[1] 16

In [56]:
library(xlsx)

In [57]:
survey.data <- read.xlsx('../data2020/survey.xlsx', 1)
head(survey.data)

ERROR: Error in loadWorkbook(file, password = password): Cannot find ../data2020/survey.xlsx
